### ISSUE TITLE
Persist selected semester in URL

### ISSUE THREAD

**Issue by jeremystucki** [lost-university/web#33]
Persist the selected semester in the URL. For example as a query parameter `?semester=5`

![image](https://github.com/lost-university/web/assets/7629727/403a25bd-bcee-4c4e-acd6-3eeae97e1114)

**Comment by StefanieJaeger** [comment]
Will tackle this issue, but will not be storing the selected semester in the url, only in the local storage.

**Comment by jeremystucki** [comment]
This will probably be done in a slightly different way together with https://github.com/lost-university/web/issues/51

**Comment by jeremystucki** [comment]
Closing in favor of https://github.com/lost-university/web/issues/43
