### ISSUE TITLE
We need to figure out how to deal with the new Studienordnung 2023

### ISSUE THREAD

**Issue by jeremystucki** [lost-university/web#51]
Announcement: [Semesterbegrüssung FS24.pdf](https://github.com/lost-university/web/files/14492775/Semesterbegrussung.FS24.pdf)

~This changes some stuff for people who started in HS23. I'm not quite sure how to handle this, we might need to add a radio button input where people can select their "Studienordnung".~

I propose we do the following steps
- [x] Add a way for people to select their starting semester. ("HS23", etc.)
       Tracking issue: https://github.com/lost-university/web/issues/43
	   Relevant PR: https://github.com/lost-university/web/pull/54
- [ ] Add support for multiple "Studienordnungen", depending on the starting semester
      - The data repository needs to be updated
        https://github.com/lost-university/data/pull/7
      - The web repository needs to be updated
        https://github.com/lost-university/web/pull/55

**Comment by misto** [comment]
Let me know if there's something unclear :-)

**Comment by jeremystucki** [comment]
@misto I now added support for the new Studienordnung. Could you please have a quick look to see if it looks correct to you?

**Comment by misto** [comment]
Looks good to me, just a few minor things:

- The "Musterpläne" dropdown uses the old names ("Data Science" is missing)
- Frontend Engineering will no longer be offered from HS24 onwards, but I guess it's fine to leave it in for now

There will be some further changes to the HS24 modules, but these are not yet final: unfortunately, MGE and PF will no longer be offered, but there will be a new module to replace them (for SE and FE) that covers UI Patterns and Frameworks.
