### ISSUE TITLE
Neue MSP wegen neuem Modul UI Patterns & Framework

### ISSUE THREAD

**Issue by joshuabeny1999** [lost-university/web#63]
Ich nehme an die MSP werden einfach überschreiben und die alten mit Mobile & GUI Engineering oder Patterns & Framework werden einfach gelöscht. 

Die Schwerpunkberechnung muss aber natürlich die alten Module berüchtsichtigen. Hier gibt es noch ein Sonderfall:
[13:55] Mirko Stocker
Ja klar, diese Anpassung sollte für niemanden einen Nachteil haben. Einen Fall haben wir noch bemerkt: wenn man SE und FE machen möchte, MGE schon gemacht hat (UIP deshalb nicht machen kann), dann könnte man den SE Schwerpunkt eigentlich nicht mehr erreichen. Im dem Fall machen wir es einfach so, dass MGE als Alternative zu PF auch für den SE Schwerpunkt zählt.
 like 1

**Comment by joshuabeny1999** [comment]
https://github.com/lost-university/web/pull/64

Dieser aktualisiert die MSP. Denke das Data-Repo muss nochmals gepullt werden und aktualisiert. Weiss aber nicht wie das machen. Dies kann sicher @jeremystucki oder @StefanieJaeger erledigen. 

Offen ist auch noch die Schwerpunktberechnung, aber da reicht vemutlich Data-Update und sollte hoffentlich korrekt im Adunis hinterlegt werden.

**Comment by jeremystucki** [comment]
Vielen Dank für das Issue & PR. Ich habe versucht die Daten zu aktualisieren, jedoch gibt es bei Adunis ein paar Inkonsistenzen.

Zum Beispiel ist das Modul "Mobile and GUI Engineering" nicht mehr gelistet unter [STD_21](https://studien.rj.ost.ch/allStudies/10191_I.html), die Studienordnung jedoch [beim Modul](https://studien.rj.ost.ch/allModules/28254_M_MGE.html). Dies führt dazu dass das Skript das Modul nicht mehr aufnimmt.

Ich warte mal ein paar Tage ab, ob das automatisch korrigiert wird. Ansonsten müssen wir uns bei der Studienadministration oder Mirko Stocker melden.

**Comment by jeremystucki** [comment]
Ich habe mal nachgefragt.
