### ISSUE TITLE
Module URL's not working anymore because of studien.rj.ost.ch change to studien.ost.ch

### ISSUE THREAD

**Issue by marcoschneider** [lost-university/web#69]
## Problem
When clicking on a Module the user lands on a 404 not found page:

<img width="971" alt="Bildschirmfoto 2024-06-06 um 10 43 20" src="https://github.com/lost-university/web/assets/25201222/2798124b-e02f-40f1-b2e1-1294a19db640">

<img width="966" alt="Bildschirmfoto 2024-06-06 um 10 44 36" src="https://github.com/lost-university/web/assets/25201222/2a35990b-35d2-49be-ace3-071f3938b16f">

## Fix
I am guessing that this is an easy fix changing the base url inside of `src/components/Module.vue`:

<img width="927" alt="image" src="https://github.com/lost-university/web/assets/25201222/083752f2-e757-43f3-9132-b7c8e9d93268">

**Comment by jeremystucki** [comment]
Closed by #70
